name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: jplaw2epub
  REGION: asia-northeast1
  JOB_NAME: epub-generator
  BUCKET_NAME: jplaw2epub-epub-storage

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Create Artifact Registry Repository (if not exists)
      run: |
        gcloud artifacts repositories describe ${{ env.JOB_NAME }} \
          --location=${{ env.REGION }} || \
        gcloud artifacts repositories create ${{ env.JOB_NAME }} \
          --repository-format=docker \
          --location=${{ env.REGION }} \
          --description="Docker repository for EPUB generator"

    - name: Build and Push Docker image
      run: |
        IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.JOB_NAME }}/${{ env.JOB_NAME }}:${{ github.sha }}"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Deploy to Cloud Run Job
      run: |
        gcloud run jobs deploy ${{ env.JOB_NAME }} \
          --image=${{ env.IMAGE_NAME }} \
          --region=${{ env.REGION }} \
          --parallelism=5 \
          --task-count=1 \
          --max-retries=2 \
          --task-timeout=3600 \
          --cpu=2 \
          --memory=1Gi \
          --set-env-vars="EPUB_BUCKET_NAME=${{ env.BUCKET_NAME }}" \
          --service-account="${{ env.JOB_NAME }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"